jwt:
  secret: mysupercomplexsecret

server:
  error:
    path: /user/error
    whitelabel:
      enabled: false

spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:mysql://127.149.99.10:3306/pfasecureapi
    password: pfaproject24
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_indentifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
     init:
       mode: never
       continue-on-error: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: sobek1127@gmail.com
    password: smbo rhcd dviw mgoh
    properties:
      mail:
        smtp:
          writetimeout: 5000
          connectiontimeout: 5000
          timeout: 5000
          auth: true
          starttls:
            enable: true
            required: true